const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Bullet,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Behaviors.Fade,
		C3.Plugins.Shape3D,
		C3.Plugins.Audio,
		C3.Plugins.TiledBg,
		C3.Behaviors.MoveTo,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Behaviors.Pin,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Bullet.Cnds.CompareTravelled,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetDistanceTravelled,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Shape3D.Acts.SetOpacity,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.ScriptsInEvents.Dasherev_Event24_Act1,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.IsCollisionEnabled,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Audio.Acts.StopAll
	];
};
self.C3_JsPropNameTable = [
	{dash: 0},
	{ativodash: 0},
	{saude: 0},
	{Plataforma: 0},
	{Projétil: 0},
	{CentrarEm: 0},
	{Dasher: 0},
	{Sólido: 0},
	{Floor1: 0},
	{Teclado: 0},
	{Esmaecer: 0},
	{Dasherrastro: 0},
	{teclaexec: 0},
	{Floor1g: 0},
	{Forma3D: 0},
	{Áudio: 0},
	{Forma3D2: 0},
	{limite: 0},
	{paredeivs: 0},
	{PlanoDeFundoEmBlocos: 0},
	{SensorA: 0},
	{sensorB: 0},
	{direcao: 0},
	{MoverPara: 0},
	{enemy: 0},
	{Âncora: 0},
	{Texto2: 0},
	{iluminacao: 0},
	{pngmonster: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{playin: 0},
	{return: 0},
	{Forma3D3: 0},
	{Sprite: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{Teclastutorial: 0},
	{txtandarfrente: 0},
	{textopular: 0},
	{textoandartras: 0},
	{Teclastutorial2: 0},
	{txtmais: 0},
	{txtmaisZ: 0},
	{txtmaisZexplicativo: 0},
	{txtmaisZexplicativo2: 0},
	{txtmaisZexplicativo3: 0},
	{sensornasce: 0},
	{nasceini: 0},
	{Fixar: 0},
	{explosiondeath: 0},
	{matarInimigo: 0},
	{Mouse: 0},
	{Sprite2: 0},
	{Playincio: 0},
	{txtdimensao: 0},
	{redimensao: 0},
	{pontosnum: 0},
	{pontostxt: 0},
	{txtfinrei: 0},
	{Texto: 0},
	{txtmaisZexplicativo4: 0},
	{cena_ativa: 0},
	{vidas: 0},
	{pontos: 0}
];

self.InstanceType = {
	Dasher: class extends self.ISpriteInstance {},
	Floor1: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Dasherrastro: class extends self.ISpriteInstance {},
	Floor1g: class extends self.ISpriteInstance {},
	Forma3D: class extends self.I3DShapeInstance {},
	Áudio: class extends self.IInstance {},
	Forma3D2: class extends self.I3DShapeInstance {},
	limite: class extends self.ISpriteInstance {},
	paredeivs: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	SensorA: class extends self.ISpriteInstance {},
	sensorB: class extends self.ISpriteInstance {},
	enemy: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	iluminacao: class extends self.ISpriteInstance {},
	pngmonster: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	playin: class extends self.ITextInstance {},
	return: class extends self.ITextInstance {},
	Forma3D3: class extends self.I3DShapeInstance {},
	Sprite: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	Teclastutorial: class extends self.ISpriteInstance {},
	txtandarfrente: class extends self.ITextInstance {},
	textopular: class extends self.ITextInstance {},
	textoandartras: class extends self.ITextInstance {},
	Teclastutorial2: class extends self.ISpriteInstance {},
	txtmais: class extends self.ITextInstance {},
	txtmaisZ: class extends self.ITextInstance {},
	txtmaisZexplicativo: class extends self.ITextInstance {},
	txtmaisZexplicativo2: class extends self.ITextInstance {},
	txtmaisZexplicativo3: class extends self.ITextInstance {},
	sensornasce: class extends self.ISpriteInstance {},
	nasceini: class extends self.ISpriteInstance {},
	explosiondeath: class extends self.ISpriteInstance {},
	matarInimigo: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Playincio: class extends self.ITextInstance {},
	txtdimensao: class extends self.ITextInstance {},
	redimensao: class extends self.ISpriteInstance {},
	pontosnum: class extends self.ITextInstance {},
	pontostxt: class extends self.ITextInstance {},
	txtfinrei: class extends self.ITextInstance {},
	Texto: class extends self.ITextInstance {},
	txtmaisZexplicativo4: class extends self.ITextInstance {}
}